// <auto-generated />
using System;
using AtlasRestaurantPOS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtlasRestaurantPOS.Web.Migrations
{
    [DbContext(typeof(AtlasRestaurantDbContext))]
    [Migration("20260915221151_CierreQuirurgicoMulticaja")]
    partial class CierreQuirurgicoMulticaja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Auditoria", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("longtext");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("longtext");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("IdEntidad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("IdSesionCaja")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdSesionCaja");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("Entidad", "IdEntidad");

                    b.HasIndex("IdUsuario", "Fecha");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Caja", b =>
                {
                    b.Property<int>("IdCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCaja"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCaja");

                    b.HasIndex("IdSucursal", "Codigo")
                        .IsUnique();

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoriaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoriaProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCategoriaProducto");

                    b.HasIndex("IdEmpresa", "Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasProducto");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Comanda", b =>
                {
                    b.Property<long>("IdComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdComanda"));

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Folio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("int");

                    b.Property<long?>("IdSesionCaja")
                        .HasColumnType("bigint");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCancelacion")
                        .HasColumnType("int");

                    b.Property<decimal>("Impuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdComanda");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdSesionCaja");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdUsuarioCancelacion");

                    b.HasIndex("IdSucursal", "Folio")
                        .IsUnique();

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.ComandaDetalle", b =>
                {
                    b.Property<long>("IdComandaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdComandaDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<long>("IdComanda")
                        .HasColumnType("bigint");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdComandaDetalle");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdProducto");

                    b.ToTable("ComandaDetalles");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.ConfiguracionPos", b =>
                {
                    b.Property<int>("IdConfiguracionPos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdConfiguracionPos"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("longtext");

                    b.HasKey("IdConfiguracionPos");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdEmpresa", "IdSucursal", "Clave");

                    b.ToTable("ConfiguracionesPos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Dispositivo", b =>
                {
                    b.Property<int>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDispositivo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Conexion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Configuracion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Identificador")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdDispositivo");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Rfc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.FolioSecuencia", b =>
                {
                    b.Property<int>("IdFolioSecuencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFolioSecuencia"));

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int>("Longitud")
                        .HasColumnType("int");

                    b.Property<string>("Prefijo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("UltimoNumero")
                        .HasColumnType("bigint");

                    b.HasKey("IdFolioSecuencia");

                    b.HasIndex("IdSucursal", "TipoDocumento")
                        .IsUnique();

                    b.ToTable("FoliosSecuencia");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Impuesto", b =>
                {
                    b.Property<int>("IdImpuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdImpuesto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<bool>("IncluidoEnPrecio")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Tasa")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("IdImpuesto");

                    b.HasIndex("IdEmpresa", "Nombre")
                        .IsUnique();

                    b.ToTable("Impuestos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.IntegracionExterna", b =>
                {
                    b.Property<int>("IdIntegracionExterna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdIntegracionExterna"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Configuracion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdIntegracionExterna");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdSucursal");

                    b.ToTable("IntegracionesExternas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMesa"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdMesa");

                    b.HasIndex("IdSucursal", "Nombre")
                        .IsUnique();

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("PermiteCambio")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdMetodoPago");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique();

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.MovimientoCaja", b =>
                {
                    b.Property<long>("IdMovimientoCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdMovimientoCaja"));

                    b.Property<string>("Concepto")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCaja")
                        .HasColumnType("int");

                    b.Property<long?>("IdSesionCaja")
                        .HasColumnType("bigint");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdMovimientoCaja");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdSesionCaja");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Pago", b =>
                {
                    b.Property<long>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdPago"));

                    b.Property<bool>("Devuelto")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("int");

                    b.Property<long>("IdComanda")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdMetodoPago")
                        .HasColumnType("int");

                    b.Property<long?>("IdSesionCaja")
                        .HasColumnType("bigint");

                    b.Property<string>("IdTransaccionExterna")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioDevolucion")
                        .HasColumnType("int");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotivoDevolucion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProveedorExterno")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdMetodoPago");

                    b.HasIndex("IdSesionCaja");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdUsuarioDevolucion");

                    b.HasIndex("IdComanda", "Devuelto");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCategoriaProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoriaProducto");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique();

                    b.HasIndex("IdEmpresa", "CodigoBarras")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.ProductoImpuesto", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdImpuesto")
                        .HasColumnType("int");

                    b.HasKey("IdProducto", "IdImpuesto");

                    b.HasIndex("IdImpuesto");

                    b.ToTable("ProductosImpuestos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.SesionCaja", b =>
                {
                    b.Property<long>("IdSesionCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdSesionCaja"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FondoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioApertura")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCierre")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoCierre")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdSesionCaja");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdUsuarioApertura");

                    b.HasIndex("IdUsuarioCierre");

                    b.ToTable("SesionesCaja");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdSucursal");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdRol");

                    b.HasIndex("UsuarioLogin")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ExistenciaInsumo", b =>
                {
                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadActual")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdSucursal", "IdInsumo");

                    b.HasIndex("IdInsumo");

                    b.ToTable("ExistenciasInsumo", (string)null);
                });

            modelBuilder.Entity("Insumo", b =>
                {
                    b.Property<int>("IdInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInsumo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<decimal>("CostoReferencia")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.HasKey("IdInsumo");

                    b.HasIndex("IdUnidadMedida");

                    b.HasIndex("Nombre");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique();

                    b.HasIndex("IdEmpresa", "CodigoBarras")
                        .IsUnique();

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("MovimientoInventario", b =>
                {
                    b.Property<long>("IdMovimientoInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdMovimientoInventario"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("CostoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExistenciaAnterior")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ExistenciaNueva")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("int");

                    b.Property<long?>("IdComanda")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdComandaDetalle")
                        .HasColumnType("bigint");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<long?>("IdSesionCaja")
                        .HasColumnType("bigint");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdMovimientoInventario");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdComandaDetalle");

                    b.HasIndex("IdSesionCaja");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdInsumo", "FechaMovimiento");

                    b.HasIndex("IdSucursal", "FechaMovimiento");

                    b.HasIndex("IdComanda", "IdInsumo", "Tipo")
                        .IsUnique();

                    b.ToTable("MovimientosInventario", (string)null);
                });

            modelBuilder.Entity("RecetaProducto", b =>
                {
                    b.Property<int>("IdRecetaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRecetaProducto"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdRecetaProducto");

                    b.HasIndex("IdInsumo");

                    b.HasIndex("IdProducto", "IdInsumo")
                        .IsUnique();

                    b.ToTable("RecetasProducto", (string)null);
                });

            modelBuilder.Entity("SecuenciasCodigo", b =>
                {
                    b.Property<int>("IdSecuenciaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSecuenciaCodigo"));

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("Longitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Prefijo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("UltimoNumero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("IdSecuenciaCodigo");

                    b.HasIndex("IdEmpresa", "TipoEntidad")
                        .IsUnique();

                    b.ToTable("SecuenciasCodigo", (string)null);
                });

            modelBuilder.Entity("UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUnidadMedida"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUnidadMedida");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique();

                    b.ToTable("UnidadesMedida", (string)null);
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Auditoria", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.SesionCaja", "SesionCaja")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdSesionCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("Empresa");

                    b.Navigation("SesionCaja");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Caja", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("Cajas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.CategoriaProducto", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Comanda", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("Comandas")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Mesa", "Mesa")
                        .WithMany("Comandas")
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.SesionCaja", "SesionCaja")
                        .WithMany("Comandas")
                        .HasForeignKey("IdSesionCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("Comandas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "Usuario")
                        .WithMany("Comandas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "UsuarioCancelacion")
                        .WithMany("ComandasCanceladas")
                        .HasForeignKey("IdUsuarioCancelacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("Mesa");

                    b.Navigation("SesionCaja");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCancelacion");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.ComandaDetalle", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Comanda", "Comanda")
                        .WithMany("Detalles")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Producto", "Producto")
                        .WithMany("ComandaDetalles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.ConfiguracionPos", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("ConfiguracionesPos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("ConfiguracionesPos")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Dispositivo", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("Dispositivos")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("Dispositivos")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.FolioSecuencia", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("FoliosSecuencia")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Impuesto", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("Impuestos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.IntegracionExterna", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("IntegracionesExternas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("IntegracionesExternas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Mesa", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("Mesas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.MetodoPago", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("MetodosPago")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.MovimientoCaja", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.SesionCaja", "SesionCaja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("IdSesionCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "Usuario")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("SesionCaja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Pago", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("Pagos")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Comanda", "Comanda")
                        .WithMany("Pagos")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.MetodoPago", "MetodoPagoCatalogo")
                        .WithMany("Pagos")
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.SesionCaja", "SesionCaja")
                        .WithMany("Pagos")
                        .HasForeignKey("IdSesionCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "UsuarioDevolucion")
                        .WithMany("PagosDevueltos")
                        .HasForeignKey("IdUsuarioDevolucion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("Comanda");

                    b.Navigation("MetodoPagoCatalogo");

                    b.Navigation("SesionCaja");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioDevolucion");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Producto", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.CategoriaProducto", "CategoriaProducto")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoriaProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaProducto");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.ProductoImpuesto", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Impuesto", "Impuesto")
                        .WithMany("ProductosImpuestos")
                        .HasForeignKey("IdImpuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Producto", "Producto")
                        .WithMany("ProductosImpuestos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Impuesto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.SesionCaja", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("SesionesCaja")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "UsuarioApertura")
                        .WithMany("SesionesCajaApertura")
                        .HasForeignKey("IdUsuarioApertura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "UsuarioCierre")
                        .WithMany("SesionesCajaCierre")
                        .HasForeignKey("IdUsuarioCierre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Sucursal", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Usuario", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ExistenciaInsumo", b =>
                {
                    b.HasOne("Insumo", "Insumo")
                        .WithMany("Existencias")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Insumo", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnidadMedida", "UnidadMedida")
                        .WithMany("Insumos")
                        .HasForeignKey("IdUnidadMedida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("MovimientoInventario", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.ComandaDetalle", "ComandaDetalle")
                        .WithMany()
                        .HasForeignKey("IdComandaDetalle")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Insumo", "Insumo")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.SesionCaja", "SesionCaja")
                        .WithMany()
                        .HasForeignKey("IdSesionCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Comanda");

                    b.Navigation("ComandaDetalle");

                    b.Navigation("Insumo");

                    b.Navigation("SesionCaja");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RecetaProducto", b =>
                {
                    b.HasOne("Insumo", "Insumo")
                        .WithMany("Recetas")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Producto", "Producto")
                        .WithMany("Recetas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("UnidadMedida", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Caja", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Comandas");

                    b.Navigation("Dispositivos");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("Pagos");

                    b.Navigation("SesionesCaja");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Comanda", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Empresa", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("ConfiguracionesPos");

                    b.Navigation("Impuestos");

                    b.Navigation("IntegracionesExternas");

                    b.Navigation("MetodosPago");

                    b.Navigation("Sucursales");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Impuesto", b =>
                {
                    b.Navigation("ProductosImpuestos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Mesa", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Producto", b =>
                {
                    b.Navigation("ComandaDetalles");

                    b.Navigation("ProductosImpuestos");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.SesionCaja", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Comandas");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Sucursal", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Cajas");

                    b.Navigation("Comandas");

                    b.Navigation("ConfiguracionesPos");

                    b.Navigation("Dispositivos");

                    b.Navigation("FoliosSecuencia");

                    b.Navigation("IntegracionesExternas");

                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Comandas");

                    b.Navigation("ComandasCanceladas");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("Pagos");

                    b.Navigation("PagosDevueltos");

                    b.Navigation("SesionesCajaApertura");

                    b.Navigation("SesionesCajaCierre");
                });

            modelBuilder.Entity("Insumo", b =>
                {
                    b.Navigation("Existencias");

                    b.Navigation("Movimientos");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("UnidadMedida", b =>
                {
                    b.Navigation("Insumos");
                });
#pragma warning restore 612, 618
        }
    }
}
