// <auto-generated />
using System;
using AtlasRestaurantPOS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtlasRestaurantPOS.Web.Migrations
{
    [DbContext(typeof(AtlasRestaurantDbContext))]
    [Migration("20260815192554_InitialRestaurantCore")]
    partial class InitialRestaurantCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Caja", b =>
                {
                    b.Property<int>("IdCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCaja"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCaja");

                    b.HasIndex("IdSucursal", "Codigo")
                        .IsUnique();

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoriaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoriaProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCategoriaProducto");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasProducto");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Comanda", b =>
                {
                    b.Property<long>("IdComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdComanda"));

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("int");

                    b.Property<long?>("IdSesionCaja")
                        .HasColumnType("bigint");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Impuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdComanda");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdSesionCaja");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.ComandaDetalle", b =>
                {
                    b.Property<long>("IdComandaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdComandaDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<long>("IdComanda")
                        .HasColumnType("bigint");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdComandaDetalle");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdProducto");

                    b.ToTable("ComandaDetalles");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Dispositivo", b =>
                {
                    b.Property<int>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDispositivo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Conexion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Configuracion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Identificador")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdDispositivo");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Rfc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.IntegracionExterna", b =>
                {
                    b.Property<int>("IdIntegracionExterna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdIntegracionExterna"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Configuracion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdIntegracionExterna");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdSucursal");

                    b.ToTable("IntegracionesExternas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMesa"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdMesa");

                    b.HasIndex("IdSucursal", "Nombre")
                        .IsUnique();

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.MovimientoCaja", b =>
                {
                    b.Property<long>("IdMovimientoCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdMovimientoCaja"));

                    b.Property<string>("Concepto")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCaja")
                        .HasColumnType("int");

                    b.Property<long?>("IdSesionCaja")
                        .HasColumnType("bigint");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdMovimientoCaja");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdSesionCaja");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Pago", b =>
                {
                    b.Property<long>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdComanda")
                        .HasColumnType("bigint");

                    b.Property<string>("IdTransaccionExterna")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProveedorExterno")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdComanda");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCategoriaProducto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoriaProducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.SesionCaja", b =>
                {
                    b.Property<long>("IdSesionCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdSesionCaja"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FondoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioApertura")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCierre")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoCierre")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdSesionCaja");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdUsuarioApertura");

                    b.HasIndex("IdUsuarioCierre");

                    b.ToTable("SesionesCaja");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdSucursal");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdRol");

                    b.HasIndex("UsuarioLogin")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Caja", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("Cajas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Comanda", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("Comandas")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Mesa", "Mesa")
                        .WithMany("Comandas")
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.SesionCaja", "SesionCaja")
                        .WithMany("Comandas")
                        .HasForeignKey("IdSesionCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("Comandas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "Usuario")
                        .WithMany("Comandas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Mesa");

                    b.Navigation("SesionCaja");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.ComandaDetalle", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Comanda", "Comanda")
                        .WithMany("Detalles")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Producto", "Producto")
                        .WithMany("ComandaDetalles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Dispositivo", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("Dispositivos")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("Dispositivos")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.IntegracionExterna", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("IntegracionesExternas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("IntegracionesExternas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Mesa", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Sucursal", "Sucursal")
                        .WithMany("Mesas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.MovimientoCaja", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.SesionCaja", "SesionCaja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("IdSesionCaja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "Usuario")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("SesionCaja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Pago", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Comanda", "Comanda")
                        .WithMany("Pagos")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Producto", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.CategoriaProducto", "CategoriaProducto")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoriaProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaProducto");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.SesionCaja", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Caja", "Caja")
                        .WithMany("SesionesCaja")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "UsuarioApertura")
                        .WithMany("SesionesCajaApertura")
                        .HasForeignKey("IdUsuarioApertura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Usuario", "UsuarioCierre")
                        .WithMany("SesionesCajaCierre")
                        .HasForeignKey("IdUsuarioCierre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Sucursal", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Usuario", b =>
                {
                    b.HasOne("AtlasRestaurantPOS.Web.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtlasRestaurantPOS.Web.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Caja", b =>
                {
                    b.Navigation("Comandas");

                    b.Navigation("Dispositivos");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("SesionesCaja");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Comanda", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Empresa", b =>
                {
                    b.Navigation("IntegracionesExternas");

                    b.Navigation("Sucursales");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Mesa", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Producto", b =>
                {
                    b.Navigation("ComandaDetalles");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.SesionCaja", b =>
                {
                    b.Navigation("Comandas");

                    b.Navigation("MovimientosCaja");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Sucursal", b =>
                {
                    b.Navigation("Cajas");

                    b.Navigation("Comandas");

                    b.Navigation("Dispositivos");

                    b.Navigation("IntegracionesExternas");

                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("AtlasRestaurantPOS.Web.Models.Usuario", b =>
                {
                    b.Navigation("Comandas");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("SesionesCajaApertura");

                    b.Navigation("SesionesCajaCierre");
                });
#pragma warning restore 612, 618
        }
    }
}
